base_url = "https://www.futuresdr.org"
build_search_index = true
compile_sass = true
generate_feeds = true
output_dir = "dist"

[markdown]
smart_punctuation = true

[markdown.highlighting]
theme = "github-light"
